### ISSUE TITLE
Roadmap 2024

### ISSUE THREAD

**Issue by ixnzh** [ByConity/ByConity#1265]
[Roadmap 2023](https://github.com/ByConity/ByConity/issues/26)

### 性能提升 | Performance improvement

- [ ] 优化动态构建filter能力 | Enhance RuntimeFilter
- [ ] 全局字典 | Global dictionary
- [ ] Zero-copy
- [ ] 非等值join算子优化 | Enhance Non-equijoin
- [ ] 并行化重构 | Parallelization Refactoring
- [ ] Bucket表优化 | Enhance Bucket Table
- [ ] UncompressedCache优化 | Enhance UncompressedCache

### 数据湖分析 | DataLake Analysis

- [ ] 支持Hive表查询、写入（Parquet和Orc格式） | Support query and insert Hive table（Parquet/Orc）
- [ ] 支持Hudi表查询、写入 | Support query and insert Hudi table
- [ ] 支持Iceberg表查询、写入 | Support query and insert Iceberg table
- [ ] 外表查询性能优化 | External Table query improvement

### 数仓能力 | Data Warehousing

- [ ] 复杂大查询ELT稳定运行 | Complex query ELT tasks for long-term stable operation
- [ ] Runtime Filter性能优化 | Enhance Runtime Filter performance
- [ ] Shuffle性能优化 | Enhance Shuffle performance
- [ ] 算子落盘 | operator spilling
- [ ] 长事务优化 | Long transaction optimization
- [ ] 失败重试 | Task auto retry
- [ ] MySQL兼容性 | MySQL compatibility
- [ ] SQL诊断优化 | SQL diagnostics and optimization suggestions

### 数据安全和备份恢复 | Data Security and Backup Recovery

- [ ] 透明加密 | Transparent encryption
- [ ] 表级快照 | Table-level snapshots
- [ ] 全量备份恢复 | Full backup and recovery

### 易用性 | Easy to use

- [ ] 一键部署 | One-step deployment
- [ ] Local mode

### 生态 | Ecosystem

- [ ] DBeaver
- [ ] Kubeblocks
- [ ] SugarBI
- [ ] Quicksight

**Comment by h8899** [comment]
May I check which items above outside contributors can work on? Or it's only for internal developers

**Comment by JackyWoo** [comment]
Please pin the issue.

**Comment by kevinthfang** [comment]
> @ixnzh May I check which items above outside contributors can work on? Or it's only for internal developers

If you are interested in any above features, or you have any inputs about other features that are not listed above, please let us know. You can also check 'good first issue' tag in the issue list that you can start the contribution right away.

**Comment by chenminghua8** [comment]
Aren’t these features already implemented in Starrocks? Why reinvent the wheel?
