### ISSUE TITLE
0.1.0-GA Release Checklist 

### ISSUE THREAD

**Issue by hustnn** [ByConity/ByConity#232]
We plan to release ByConity GA version by the end of May, we made a checklist here and expect to finish them before 15/May/2023.

The checklist includes 4 parts, stability, performance improvement, benchmark, document and new features. 

# Stability
- [x] #237
- [x] #239
- [x] #238

# Performance improvement
- [x] #205
- [x] #240
- [x] #241

# Benchmark
- [x] #242
- [x] Compare ByConity performance with in-house version
- [x] #243

# Doc
- [x] #244
- [x] #245

# New features  
- [x] Provide binary install package https://github.com/ByConity/ByConity/pull/105
- [x] Data cache preload https://github.com/ByConity/ByConity/pull/189
- [x] HDFS kerberos support https://github.com/ByConity/ByConity/pull/194
- [x] #246
- [x] Support ORC for HIVE external table (preview) https://github.com/ByConity/ByConity/pull/201
- [x] #248

**Comment by WillemJiang** [comment]
@hustnn  Could you add the PR links below the task which is closed to keep the track of the code？

**Comment by hustnn** [comment]
The progress is tracked in https://github.com/ByConity/ByConity/milestone/1
